### ISSUE TITLE
[feature-request] Disable "showing of map"?

### ISSUE THREAD

**Issue by himpich** [shudnal/NomapPrinter#1]
Hi, thanks for the Addon!
I use it to display my "nomap" progress to my stream viewers. (save file, upload it automatically to webhost, display it there)
Would it be possible to add a configuration to disable the map display (default key m)? I accidently press m sometimes with my run and it would help if it does not respond :)

Thanks in advance

**Comment by shudnal** [comment]
Ok that's easy. I'll make new version soon.

**Comment by shudnal** [comment]
Pls check 1.0.7 version
