### ISSUE TITLE
When opening the interactive map at the cartography table using GamePad a pin is created automatically

### ISSUE THREAD

**Issue by ZenDragonX** [shudnal/NomapPrinter#10]
When the interactive map is opened at the table using the gamepad the interact button (btn:A) is also the drop pin button (btn:A) so a pin is automatically created when the player opens the map using the gamepad because when the map opens the button is already pressed.  With a keyboard the interact button (E) is not the same as the create pin button (double click).

Suggested fix:   Maybe just have a timer that blocks pin creation for a second after the interactive map is opened?  That should be enough time to release the button so that it doesn't automatically add a pin as soon as the map opens.

My config settings are to reverse left and right sides of the table interaction.  Not sure if this makes a difference.

**Comment by shudnal** [comment]
Fixed in 1.1.5
