### ISSUE TITLE
dedicated server nomap mode shows white blank instead of "you don't have a map yet"

### ISSUE THREAD

**Issue by ZenDragonX** [shudnal/NomapPrinter#12]
when connecting to a dedicated server and the server is in nomap mode there is a blank white box when the player presses M instead of showing the text "no map created yet"

this does not happen on a local play.

**Comment by shudnal** [comment]
Are you sure you didn't set "Data storage" to LoadFromSharedFile? Or Local folder and the file in the folder are blank?

**Comment by ZenDragonX** [comment]
Data storage is set to LocalFolder.  How did blank white images get generated?  Shouldn't it not generate anything until a cartography table is available?

**Comment by ZenDragonX** [comment]
I think MAYBE what happeend is that I was testing offline with the same map and I set exploremap true offline to see the whole map.  Then when i went online with admin character it somehow used that setting?  I'm not entirely sure.  I was able to remove the problem by erasing the blank png from the local folder and quitting the game and logging back in.  I'm still not sure how the blank white map got created in the first place though since there is no cartogrphay table in the world.  It was my understanding that the png file gets written when the cartography table is interacted with, correct?

**Comment by ZenDragonX** [comment]
seems to only happen if i login as admin.  Doesn't seem to generate the .png if i am not logged in as admin.

EDIT:  Nope, seems to happen even if i am not admin.  Logging out and logging back in seems to have generated a blank .png.  I am using Vanilla rendering mode LocalStorage folder.

**Comment by shudnal** [comment]
Exploring or resetting map have no influence to map generation process outside of showing fog.
In general Vanilla map works the way like opening the map window for 1 frame and doing a screenshot of showed map.
Do you have any mod altering the map showing process?
Do you have an errors or warnings in the log?
Do you have filesystem access to set directory?
