### ISSUE TITLE
map bitmap is partially corrupted in Valheim test release 0.219.10

### ISSUE THREAD

**Issue by daftdan** [shudnal/NomapPrinter#14]
The mod appears to function as it has before until the in-game map is opened, revealing strange rendering artefacts:
![image](https://github.com/user-attachments/assets/000cb8c2-fdc4-41f9-bb38-86e76fe996a5)
Also, it is not producing .png files in the `screenshots` directory as it used to with normal version of Valheim. This happens with NomapPrinter v1.3.6 and v1.3.5. I'm running Valheim Linux native version from Steam on Fedora 40.

**Comment by shudnal** [comment]
I have no idea what's happening if you have no errors in log file.
You can try clearing cache located in `...\BepInEx\cache\shudnal.NomapPrinter`

**Comment by daftdan** [comment]
The following is repeated multiple times in Player.log:
```[Error  : Unity Log] MissingMethodException: Method not found: single .ZInput.GetAxis(string)
Stack trace:
NomapPrinter.MapViewer.Update () (at <3f7f1f2d4d224a59afdc9ec4848a9b17>:0)
NomapPrinter.NomapPrinter.Update () (at <3f7f1f2d4d224a59afdc9ec4848a9b17>:0)

MissingMethodException: Method not found: single .ZInput.GetAxis(string)
  at NomapPrinter.MapViewer.Update () [0x00153] in <3f7f1f2d4d224a59afdc9ec4848a9b17>:0 
  at NomapPrinter.NomapPrinter.Update () [0x00022] in <3f7f1f2d4d224a59afdc9ec4848a9b17>:0

**Comment by shudnal** [comment]
Ah I somehow missed. Yes it's broken for current PTB. I will fix this when
it comes live.

пт, 18 окт. 2024 г., 20:13 Daniel Challen ***@***.***>:

**Comment by shudnal** [comment]
1.3.7 should work on PTB. But I didn't change anything related to wrong image issue.

**Comment by daftdan** [comment]
This problem (corrupted map, missing png file) is still occurring with the newly-released Patch 0.219.13 – The Bog Witch

**Comment by shudnal** [comment]
Well without any info on the issue I can't even start to investigate.
I can't reproduce it myself so you have to do at least some basic  actions like enable logging and send a log file, trying other worls, other character, other data storage settings or other OS with the same world and character.

**Comment by daftdan** [comment]
The problem appears to only affect one world/server. A fresh no-map world doesn't have the problem, but a fresh character on the existing world does have a strangely rendered map. I don't have easy access to other machines to test, but I will ask if one of my friends can install the mod and replicate the issue. 
[Player.log](https://github.com/user-attachments/files/17607919/Player.log)
![Chart TPB Community](https://github.com/user-attachments/assets/ba50bc8d-127d-4e4e-8f0d-9c7b56b8989a)
For now, however, I guess we can close the issue unless I get more concrete information.

**Comment by shudnal** [comment]
Did you try to delete cache? At ...\BepInEx\cache\shudnal.NomapPrinter

**Comment by daftdan** [comment]
> Did you try to delete cache? At ...\BepInEx\cache\shudnal.NomapPrinter

Well I am idiot, I missed your earlier comment about clearing cache. That has made the problem go away, thank you. Sorry for taking your time.

**Comment by shudnal** [comment]
Damn that's good news. I started to thinking something is wrong an this looks like malformed cache somehow. Or version difference idk. If you have another OS related issue don't afraid to ask again. This issue is really closed now.
