### ISSUE TITLE
Wrong Map Loading

### ISSUE THREAD

**Issue by kittycat377** [shudnal/NomapPrinter#15]
Hello! 

Recently with the bog witch update we updated the mod to its newest version on both server side as well as client side and it worked as intended, but for some reason tonight the map is suddenly showing up as a different world?  Tried wiping all the old .ddl files but the problem is still there.   Any ideas on what to try?

**Comment by shudnal** [comment]
In any case of malformed map first step is to clear cache located at `...\BepInEx\cache\shudnal.NomapPrinter` and redraw map.
