### ISSUE TITLE
no map printer not removing pins i have deleted 

### ISSUE THREAD

**Issue by Malvorn** [shudnal/NomapPrinter#17]
Hi how can i remove pins i dont need anymore?
i was using autopins signs
but when i remove them the pin stays even is a redrawn my map several times

**Comment by shudnal** [comment]
What do you do exactly to remove pin?

**Comment by shudnal** [comment]
Most convenient way to operate pins you don't need is to enable config value "Show interactive map on record discoveries" and remove redundant or outdated pins from there.
If you use autopinsigns the only way to remove pin is to remove sign. I didn't come up with better solution yet.

**Comment by Malvorn** [comment]
I remove the sign with hammer. (sometimes the pin disappears sometimes not)

anyway  "Show interactive map on record discoveries"  helps so its a possible workaround as you suggested.

my game setting is NOMAP mode
using autopinsigns with nomap printer...
so somewhat is "cheating" the interactive map but i can live with this :)

thanks you for the prompt suggestion

**Comment by Malvorn** [comment]
i think i will try if there is any difference if i delete the pin message, then remove the sign with hammer

**Comment by shudnal** [comment]
Pin handling is not very well done in vanilla game itself. I'll try to come up with more stable solution to sync pins added through signs. And if you use cartography table in multiplayer then there is an extra level of wonkiness in shared pins management.
