### ISSUE TITLE
NoMapPrinter + Jewelcrafting/EpicLoot

### ISSUE THREAD

**Issue by zem-sessions** [shudnal/NomapPrinter#2]
`[Error  : Unity Log] ArgumentException: RenderTextureDesc width must be greater than zero.
Parameter name: desc.width
Stack trace:
UnityEngine.RenderTexture.ValidateRenderTextureDesc (UnityEngine.RenderTextureDescriptor desc) (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.RenderTexture.GetTemporary (UnityEngine.RenderTextureDescriptor desc) (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.RenderTexture.GetTemporaryImpl (System.Int32 width, System.Int32 height, System.Int32 depthBuffer, UnityEngine.Experimental.Rendering.GraphicsFormat format, System.Int32 antiAliasing, UnityEngine.RenderTextureMemoryless memorylessMode, UnityEngine.VRTextureUsage vrUsage, System.Boolean useDynamicScale) (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.RenderTexture.GetTemporary (System.Int32 width, System.Int32 height, System.Int32 depthBuffer, UnityEngine.RenderTextureFormat format, UnityEngine.RenderTextureReadWrite readWrite) (at <80fe1a4e36fe44618284312cb721a597>:0)
NomapPrinter.NomapPrinter+MapGeneration.GetReadableTexture (UnityEngine.Texture2D texture) (at <b59ed1844edc4fab9425b9039605ea6c>:0)
NomapPrinter.NomapPrinter+MapGeneration.GetTextureFromSprite (UnityEngine.Sprite sprite) (at <b59ed1844edc4fab9425b9039605ea6c>:0)
NomapPrinter.NomapPrinter+MapGeneration.GetIconPixels (UnityEngine.Sprite icon, System.Int32 targetX, System.Int32 targetY) (at <b59ed1844edc4fab9425b9039605ea6c>:0)
NomapPrinter.NomapPrinter+MapGeneration.AddPinIconToCache (UnityEngine.Sprite icon) (at <b59ed1844edc4fab9425b9039605ea6c>:0)
NomapPrinter.NomapPrinter+MapGeneration.IsShowablePinIcon (Minimap+PinData pin) (at <b59ed1844edc4fab9425b9039605ea6c>:0)
NomapPrinter.NomapPrinter+MapGeneration.GetPinsToPrint () (at <b59ed1844edc4fab9425b9039605ea6c>:0)
NomapPrinter.NomapPrinter+MapGeneration+<Go>d__5.MoveNext () (at <b59ed1844edc4fab9425b9039605ea6c>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <80fe1a4e36fe44618284312cb721a597>:0)`

The mod works great until I start changing some of the configuration options with the pins and then I get an error like this requiring a client restart. I can't produce it on demand though, so I'm unsure what's causing it. I receive a similar error when trying to use it with Epic Loot pertaining to desc.width, so I'm hoping the issue could be fixed without having to add mod support or the likes. Is there any information I can provide to help debug this, if you're willing to tackle it?

**Comment by shudnal** [comment]
I think this is enough.

**Comment by shudnal** [comment]
Pls check if https://github.com/shudnal/NomapPrinter/releases/download/1.0.10/NomapPrinter.dll works
It's not published yet so you have to manually replace the file.

**Comment by rcasstevens** [comment]
Sorry, I'm just now coming across this. I'll check it out now!

**Comment by zem-sessions** [comment]
Sorry for the late response, only just came across your reply. I'm unable to reproduce the error, and no manner of my fiddling seems to break it. I believe it's fixed, thanks!
