### ISSUE TITLE
File destination folder does not get automatically created, please create AppData\LocalLow\IronGate\Valheim\screenshots\ if needed

### ISSUE THREAD

**Issue by shodanx2** [shudnal/NomapPrinter#5]
Original title of this issue was
Unable to save map file when using linux dedicated server ??

However, as I documented the issue, I now realise the problem is the file destination folder is not being create if missing

Here are my settings

![2023-11-20 00_40_05-Valheim](https://github.com/shudnal/NomapPrinter/assets/10621885/93612e05-f038-41e6-89b2-5891772b709d)

When I try to create a saved map file, I have enabled "Save to file"

I have tried leaving "save to file path" blank, 

I have tried to set a folder I know I can write c:\users\myusername\
I have tried to set a folder I know I can write c:\users\myusername\myfile

But I didn't get a file

I realized in the server logs that it was actually trying to save the file on the server !

So I tried to set my worldsave folder \valheim_worlds\ for the path, but this still creates an error

Because it's now trying to save to d:\valheim_worlds\ on the linux server instead of the real path of \valheim_worlds\

Here is the actual error message
```

[Info   : Unity Log] 11/20/2023 00:26:13: tip:$loadscreen_tip04

[Info   : Unity Log] 11/20/2023 00:26:21: Spawned after 8.019994

[Info   : Unity Log] 11/20/2023 00:26:23: Skipping unloading unused assets

[Info   : Unity Log] 11/20/2023 00:26:23: Minimap: Adding unique location (-4.16, 38.86, -1.82)

[Info   : Unity Log] 11/20/2023 00:26:23: Minimap: Adding unique location (4877.22, 34.69, -1927.25)

[Error  : Unity Log] DirectoryNotFoundException: Could not find a part of the path "D:\valheim_worlds\BirdsEye map of FliShoLand.png".
Stack trace:
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.IO.File.InternalWriteAllBytes (System.String path, System.Byte[] bytes) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.IO.File.WriteAllBytes (System.String path, System.Byte[] bytes) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
NomapPrinter.NomapPrinter+MapGeneration.SaveMapTexture (System.String path, NomapPrinter.NomapPrinter+MapType mapType, UnityEngine.Color32[] map) (at <3de038965f8f48faa4ca6e4195f6f91a>:0)
NomapPrinter.NomapPrinter+MapGeneration+<Go>d__5.MoveNext () (at <3de038965f8f48faa4ca6e4195f6f91a>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <50b18efe22344b9eb3b7d77b08ea287f>:0)

[Warning: Unity Log] 11/20/2023 00:26:43: Set button "CamZoomIn" to None!

[Warning: Unity Log] 11/20/2023 00:26:43: Set button "CamZoomOut" to None!

[Info   : Unity Log] 11/20/2023 00:26:43: Current res 3840x2160     3840x2160
```

On the server
![2023-11-20 00_46_13-BepInEx 5 4 22 0 - Valheim Server -](https://github.com/shudnal/NomapPrinter/assets/10621885/7e34ab16-763e-443d-acbc-ee3099098201)

on the client

![2023-11-20 00_45_57-Valheim](https://github.com/shudnal/NomapPrinter/assets/10621885/13401c7e-f9c3-44c1-ad11-6ee175aaed65)

Well, I'm really not sure if that's happenning on the client or the server ...

I decided to create the folder d:\valheim_worlds\ and surprise, it works !

![2023-11-20 00_53_03-BirdsEye map of FliShoLand png - IrfanView (Zoom_ 16667 x 16667)](https://github.com/shudnal/NomapPrinter/assets/10621885/8071ab81-010b-41d9-b131-9748463e6ce3)

Not sure why I wasn't getting the files initially now ...

I will set the save path back to blank

![2023-11-20 00_58_53-Valheim](https://github.com/shudnal/NomapPrinter/assets/10621885/b431d73c-56e6-46ec-bbaa-d9bbe9b320e9)

![2023-11-20 00_59_49-Valheim](https://github.com/shudnal/NomapPrinter/assets/10621885/a2141679-53e8-4797-ba4d-33425113e66a)

Ah I see now, it's trying to save to 

C:\Users\user\AppData\LocalLow\IronGate\Valheim\screenshots\

But that folder doesn't exist ? Why didn't it create it ? 

C:\Users\user\AppData\LocalLow\IronGate\Valheim\ does exist

So, I created the folder and now it works 
![BirdsEye map of FliShoLand cr](https://github.com/shudnal/NomapPrinter/assets/10621885/63beb77c-1b06-4b22-8d00-4f0c472f0a49)
![Chart map of FliShoLand cr](https://github.com/shudnal/NomapPrinter/assets/10621885/b17720e7-b686-427b-aa6f-83a254e9e66c)
![OldChart map of FliShoLand cr](https://github.com/shudnal/NomapPrinter/assets/10621885/c800089a-f914-42a1-9b7d-12d6b92e3741)
![Topographical map of FliShoLand cr](https://github.com/shudnal/NomapPrinter/assets/10621885/98339ed8-cf6b-4289-9b4c-b0616101843d)

**Comment by shudnal** [comment]
The mod shouldn't do anything server side except sharing between settings and loading shared map from file at settings "Load map from file". Interaction with map table which is starting the process of map creating is purely clientsided.

Yes by default my mods aren't creating any folders and objects except given in the settings. So if you have no folder for file there will be an error you should handle. It's to prevent unnessesary damage to file system by unexperienced user.

And you handled it well. I don't feel I have to change anything at this point.
