### ISSUE TITLE
Feature Request: Incorporate TargetPortal pins into the static map.

### ISSUE THREAD

**Issue by ZenDragonX** [shudnal/NomapPrinter#8]
The mod Target Portal adds custom swirly portal pins to the dynamic map automatically whenever you create/destroy a portal.  They can be viewed by pressing P (Default hotkey).  It would be really cool if these icons could be added to the generated static map as well via a config option if the mod is present.  

Bonus: A way to have them always display automatically when interacting with the dynamic map so that you don't have to press the hotkey to show them when first opening the map.

Hope this is easy to do!  Love your mod! Good stuff! :)

**Comment by shudnal** [comment]
Mod will support any external pins if it used like usual pins. As I can see TargetPortal's pins should be visible if you toggle pins visibility in the interactive map.

**Comment by ZenDragonX** [comment]
Yes the pins are visible on the interactive map but not the static map.  Unless that’s now possible with 1.1.2? I haven’t tested with latest version.

**Comment by shudnal** [comment]
I'll check again the TargetPortal code.

**Comment by shudnal** [comment]
TargetPortal adds pins on the map only if it is showing when teleporting. There are no public methods to add and hide its pins which I could invoke to control pins. Only private methods which I can't and shoudn't call.
And there is complex and fine logic the pin list is formed to just duplicate it on my side.
So for now there is no easy way to add TargetPortal's pins.
