### ISSUE TITLE
Bug: Does not block access when inside a Ward

### ISSUE THREAD

**Issue by ZenDragonX** [shudnal/NomapPrinter#9]
Please add a config option to respect wards and prevent access when inside a Ward that the player does not have permission for.

Great job btw!  All the other stuff we talked about seems to work great! :)

Are you on Discord?

**Comment by shudnal** [comment]
I thought table access was already restricted. I will add that options.

**Comment by ZenDragonX** [comment]
It does say "no access" but the write section of the table still makes the static map draw and flashes something really fast on the screen that I can't see and freezes for a second so it feels like it's drawing the map.  When interacting with the interactive area to view the map it just shows the interactive map even though the tooltip says no access.  (I use the reversed logic and the "read map" portion if that makes a difference)

Still seems to be responding to the interact behavior.

**Comment by shudnal** [comment]
Ah I got it. Will fix

**Comment by shudnal** [comment]
Fixed in 1.1.3

**Comment by ZenDragonX** [comment]
Getting error when it loads.  I sent you details on discord.

**Comment by shudnal** [comment]
Got it fixed
